### ISSUE TITLE
Valeur par défaut de la variable schéma

### ISSUE THREAD

**Issue by ghost** [notpixxl/postgresqlprivs#1]
Bonjour,

Si on défini schéma lorsque qu'on met des droits sur une database, on rencontre une erreur.
Par exemple :
```
- name: GRANT ALL PRIVILEGES ON DATABASE library TO librarian
  community.general.postgresql_privs:
    db: library
    privs: ALL
    type: database
    role: librarian
```

ici avec ce rôle, la variable sera donc défini par défaut sur la valeur 'public', alors qu'elle ne doit pas être défini.

J'ai corrigé le problème en remplaçant la valeur par défaut par omit : 
`schema: "{{ item.schema | default(omit) }}"`

Cordialement.
